version: "3.9"

services:
  frontend:
    platform: linux/amd64
    restart: always
    container_name: "frontend"
    image: zentrace/frontend
    build: https://github.com/zenchain-protocol/zentrace-frontend.git
    env_file:
      - ../envs/common-frontend.env
