version: "3.9"

services:
  visualizer:
    platform: linux/amd64
    restart: always
    container_name: "visualizer"
    image: zentrace/visualizer
    build: https://github.com/zenchain-protocol/zentrace-rs.git#main:visualizer
    env_file:
      - ../envs/common-visualizer.env
